replicaCount: 1

image:
  repository: harbor.k8s.elab.rs/bolnica-1/laboratory
  pullPolicy: Always
  tag: "latest"
  
env:
  springDatasourceUrl: jdbc:mysql://bolnica-1-mysql2:3306/laboratory?createDatabaseIfNotExist=true
  employeesServiceUrl: http://employees-service:8080/api
  patientsServiceUrl: http://patients-service:8081/api
  activemqUrl: tcp://activemq:61616

service:
  type: ClusterIP
  name: laboratory-service
  port: 8083
  targetPort: 8083

