apiVersion: v1
data:
  # rootHost: %
  rootHost: JQ==
  # rootPassword: admin
  rootPassword: YWRtaW4=
  # rootUser: root
  rootUser: cm9vdA==
kind: Secret
metadata:
  name: bolnica-1-mysql-creds
  namespace: bolnica-1-dev
---
apiVersion: mysql.oracle.com/v2
kind: InnoDBCluster
metadata:
  name: bolnica-1-mysql
  namespace: bolnica-1-dev
spec:
  secretName: bolnica-1-mysql-creds
  tlsUseSelfSigned: true
  instances: 3
  router:
    instances: 1
