apiVersion: v1
kind: Service
metadata:
  labels:
    app: infirmary-service
  name: infirmary-service
  namespace: bolnica-1-dev
spec:
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: {{ .Values.service.targetPort }}
  selector:
    app: infirmary-service
  type: {{ .Values.service.type }}

