apiVersion: v1
kind: Service
metadata:
  labels:
    app: covid-service
  name: covid-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 9000 
      protocol: TCP
      targetPort: 9000
  selector:
    app: covid-service
  type: {{ .Values.service.type }}
