apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: employees-service
  name: employees-{{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount  }}
  selector:
    matchLabels:
      app: employees-service
  template:
    metadata:
      labels:
        app: employees-service
    spec:
      containers:
        - image: "{{ .Values.image.repository }}/employees:{{ .Values.image.tag  }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Chart.Name  }}
          env:
            - name: spring.profiles.active
              value: dev
            - name: spring.datasource.url
              value: {{ .Values.env.employeesDBUrl }}
            - name: spring.datasource.username
              value: root
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: mariadb-bolnica-1-creds
                  key: password
            - name: spring.redis.host
              value: redis
          ports:
            - containerPort: 8080
