apiVersion: v1
kind: Service
metadata:
  labels:
    app: employees-service
  name: employees-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 8080 
      protocol: TCP
      targetPort: 8080
  selector:
    app: employees-service
  type: {{ .Values.service.type }}

