apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: infirmary-service
  name: infrimary-{{ .Release.Name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: infirmary-service
  template:
    metadata:
      labels:
        app: infirmary-service
    spec:
      containers:
        - image: "{{ .Values.image.repository }}/infirmary:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: {{ .Chart.Name }}
          env:
            - name: spring.activemq.broker.url
              value: {{ .Values.env.activemqUrl }}
            - name: SPRING_ACTIVEMQ_BROKER_URL
              value: {{ .Values.env.activemqUrl }}
            - name: employee.service.url
              value: {{ .Values.env.employeesServiceUrl}}
            - name: patients.service.url
              value: {{ .Values.env.patientsServiceUrl }}
            - name: laboratory.service.url
              value: {{ .Values.env.laboratoryServiceUrl }}
            - name: spring.profiles.active
              value: dev
            - name: spring.datasource.url
              value: {{ .Values.env.infirmaryDBUrl }}
            - name: spring.datasource.username
              valueFrom:
                secretKeyRef:
                  name: bolnica-1-mysql-creds
                  key: rootUser
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: bolnica-1-mysql-creds
                  key: rootPassword
            - name: spring.redis.host
              value: redis
          ports:
            - containerPort: 8084

