apiVersion: v1
kind: Service
metadata:
  labels:
    app: infirmary-service
  name: infirmary-service
  namespace: {{ .Values.namespace  }}
spec:
  ports:
    - port: 8084
      protocol: TCP
      targetPort: 8084 
  selector:
    app: infirmary-service
  type: {{ .Values.service.type }}

