apiVersion: v1
kind: Service
metadata:
  labels:
    app: laboratory-service
  name: laboratory-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 8083
      protocol: TCP
      targetPort: 8083
  selector:
    app: laboratory-service
  type: {{ .Values.service.type }}


