apiVersion: v1
kind: Service
metadata:
  labels:
    app: patients-service
  name: patients-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: patients-service
  type: {{ .Values.service.type }}

