replicaCount: 1
namespace: bolnica-1-dev
domain: bolnica-1-dev.k8s.elab.rs

image:
  repository: harbor.k8s.elab.rs/bolnica-1
  pullPolicy: Always
  tag: "dev"
  
env:
 #employeesDBUrl: jdbc:mysql://bolnica-1-mysql:3306/employees?createDatabaseIfNotExist=true
 #patientsDBUrl: jdbc:mysql://bolnica-1-mysql:3306/patietns?createDatabaseIfNotExist=true
 #laboratoryDBUrl: jdbc:mysql://bolnica-1-mysql:3306/laboratory?createDatabaseIfNotExist=true
 #infirmaryDBUrl: jdbc:mysql://bolnica-1-mysql:3306/infirmary?createDatabaseIfNotExist=true

  employeesDBUrl: jdbc:mysql://primary-mariadb-bolnica-1:3306/employees
  patientsDBUrl: jdbc:mysql://primary-mariadb-bolnica-1:3306/patients
  laboratoryDBUrl: jdbc:mysql://primary-mariadb-bolnica-1:3306/laboratory
  infirmaryDBUrl: jdbc:mysql://primary-mariadb-bolnica-1:3306/infirmary
  covidDBUrl: mongodb://username:password@covid-mongodb-sharded:27017

  employeesServiceUrl: http://employees-service:8080/api
  patientsServiceUrl: http://patients-service:8081/api
  laboratoryServiceUrl: http://laboratory-service:8083/api
  infirmaryServiceUrl: http://infirmary-service:8084/api
  activemqUrl: tcp://activemq:61616

service:
  type: ClusterIP

