replicaCount: 1

image:
  repository: harbor.k8s.elab.rs/bolnica-1/patients
  pullPolicy: Always
  tag: "latest"

env:
  springDatasourceUrl: jdbc:mysql://bolnica-1-mysql2:3306/patients?createDatabaseIfNotExist=true
  employeesServiceUrl: http://employees-service:8080/api
  laboratoryServiceUrl: http://laboratory-service:8083/api
  activemqUrl: tcp://activemq:61616

service:
  type: ClusterIP
  name: patients-service
  port: 8081
  targetPort: 8081

