apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: laboratory-service
  name: laboratory-service
  namespace: bolnica-1-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laboratory-service
  template:
    metadata:
      labels:
        app: laboratory-service
    spec:
      containers:
        - image: harbor.k8s.elab.rs/bolnica-1/laboratory:0.0.3
          imagePullPolicy: Always
          name: laboratory-service
          env:
            - name: spring.activemq.broker.url
              value: tcp://activemq:61616
            - name: SPRING_ACTIVEMQ_BROKER_URL
              value: tcp://activemq:61616
            - name: employee.service.url
              value: http://employees-service:8080/api
            - name: patients.service.url
              value: http://patients-service:8081/api
            - name: spring.profiles.active
              value: dev
            - name: spring.datasource.url
              value: jdbc:mysql://bolnica-1-mysql2:3306/laboratory?createDatabaseIfNotExist=true
            - name: spring.datasource.username
              valueFrom:
                secretKeyRef:
                  name: bolnica-1-mysql-creds
                  key: rootUser
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: bolnica-1-mysql-creds
                  key: rootPassword
            - name: spring.redis.host
              value: redis
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  labels: 
    app: laboratory-service
  name: laboratory-service
  namespace: bolnica-1-dev
spec:
  ports: 
    - port: 8083
      protocol: TCP
      targetPort: 8083
  selector:
    app: laboratory-service
  type: ClusterIP
